# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Business and Technology
tagline:          'Business and Technology'
description:      'Blog about Business and Technology'
url:              'http://ambarishg.github.io'
baseurl:          'http://ambarishg.github.io'

author:
  name:           'Ambarish Ganguly'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://github.com/ambarishg.github.io
  
 # Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  
markdown:         kramdown
highlighter:      rouge
